import type { NextPage } from 'next';
import Head from 'next/head';
import AboutUS from '../components/aboutus';
import ContactUs from '../components/contactus';
import Footer from '../components/footer';
import Masthead from '../components/masterhead';
import Skills from '../components/skills';
import TrustedBy from '../components/trusedby';
import Works from '../components/works';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Margelo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Masthead />
      <AboutUS />
      <Skills />
      <Works />
      <TrustedBy />
      <ContactUs />
      <Footer />
    </div>
  );
};

export default Home;
